# CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0 for more details
#
# This is mainly taken from
# https://vsupalov.com/build-docker-image-with-circle-ci-2-push-to-google-container-registry/
# and adapted to our needs, especially with enhancements from
# https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/
# Thanks for the awesome preparation.
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: wekan
      TAG: latest
    docker:
      - image: circleci/buildpack-deps:focal

workflows:
  build_and_deploy:
    jobs:
      - build:
          context: Docker publishing as bludoc
      - test_and_deploy:
          context: Docker publishing as bludoc
          requires:
            - build

jobs:
  build:
    executor: docker-publisher
    working_directory: ~/repo
    steps:
      - checkout

      # This builds the image. Taken from
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker

      # Build image.
      - run:
          name: Build image
          no_output_timeout: 50m
          command: |
            docker build -t $DOCKER_USER/$IMAGE_NAME:$TAG .

      # Save the image.
      - run:
          name: Save Docker image
          command: docker save -o image.tar $DOCKER_USER/$IMAGE_NAME:$TAG

      # Permanently store the built image to test and potentially deploy it.
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  test_and_deploy:
    executor: docker-publisher
    working_directory: ~/repo
    steps:

      # Attach workflow workspace to retrieve saved image.
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      # Retrieve built and stored image.
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar

      # Test image.
      - run:
          name: Test images
          command: |
            docker run -d $DOCKER_USER/$IMAGE_NAME:$TAG
            docker ps | grep $TAG

      # Push image.
      - run:
          name: Push image
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker push $DOCKER_USER/$IMAGE_NAME:$TAG
